### ISSUE TITLE
Gather further data

### ISSUE THREAD

**Issue by MartinWilden** [Phype/purei9_unofficial#1]
@Phype Many thanks for the project!

Is it possible to request further data like the charge state or the current position and map of the robot?

**Comment by Phype** [comment]
I haven't seen a way to get this data directly from the robot. The cloud definitely has it, but this project is/was focused more on communicating with the robot directly, ie. in case the cloud stops working.

The robot interface has some more commands, there are even command which names indicate that you could steer the robot manually, but since the purei9 app doesn't use them, there is no proper way to find out how they work (except reverse engineering a purei9 Firmware image, which is not how i want to spend my free time).

If you want to do some some resaerch on the local robot interface yourself, i can provide some pointers where to start, but since doing so is a legal grey area in many countries, i don't want to share this in the public. The EU has laws which essentially allow reverse engineering when it's done for interoperability, but still, i don't really am interested in going to court for this.

**Comment by MartinWilden** [comment]
Thank you very much for the quick answer. 

I am also interested in an integration into the Home Assistant. So for me, a solution via the cloud would be sufficient (at least for now and when the cloud is stable). But I couldn't find any documentation of the API.

**Comment by Phype** [comment]
There is no documentation. For both the cloud API or robot network interface you need to reverse engineer the app to find out more about what is happening. I only did this for the cloud up to the point where it exposed the `local robot pw`, which is needed to connect locally.

**Comment by Phype** [comment]
I added some functionality to get map PNGs from the cloud, but to properly show them (including a icon for where the robot and base station is, etc.) you would need to develop a UI of some sort, which definitely is out of scope of this project.

**Comment by Phype** [comment]
I'll close this for now. If you have requests for specific functionality, please open another issue.
