### ISSUE TITLE
Start spot cleaning

### ISSUE THREAD

**Issue by drgreenbaum** [Phype/purei9_unofficial#13]
Implement command for starting a spot cleaning. It is cleaning a area of 1x1 meter area but 2 times.

**Comment by Phype** [comment]
I haven't considered adding this because i wasn't sure why you would trigger that when you have to position the robot anyway. But now it's there, i think it should work for local and cloud v1, not sure about cloud v2.

Actually, the wellbeing App doesn't seem to have this feature either, so not sure if its even possible to trigger it via that API.

In the other APIs the command are there, so it should work - i haven't tested it though because it's late and i don't want to annoy my neighbors :)
